// Generated by C4Studio.
//
// DO NOT MODIFY, your changes will be lost when this file is regenerated.
//

import UIKit


@IBDesignable
public class BeginView: UIView {
    public struct Defaults {
        public static let size = CGSize(width: 375.0, height: 667.0)
        public static let backgroundColor = UIColor.whiteColor()
    }

    public var tile23: ShapeView!
    public var tile22: ShapeView!
    public var tile21: ShapeView!
    public var tile20: ShapeView!
    public var tile19: ShapeView!
    public var tile18: ShapeView!
    public var tile17: ShapeView!
    public var tile16: ShapeView!
    public var tile14: ShapeView!
    public var tile13: ShapeView!
    public var tile12: ShapeView!
    public var tile11: ShapeView!
    public var tile10: ShapeView!
    public var tile15: ShapeView!
    public var tile9: ShapeView!
    public var tile3: ShapeView!
    public var tile8: ShapeView!
    public var tile7: ShapeView!
    public var tile6: ShapeView!
    public var tile5: ShapeView!
    public var tile1: ShapeView!
    public var tile4: ShapeView!
    public var tile2: ShapeView!
    public var tile24: ShapeView!
    public var tile25: ShapeView!
    public var tile26: ShapeView!

    public override init(frame: CGRect) {
        super.init(frame: frame)
        createViews()
    }

    public required init?(coder: NSCoder) {
        super.init(coder: coder)
        backgroundColor = Defaults.backgroundColor
        createViews()
    }

    func createViews() {
        tile23 = ShapeView(frame: CGRect(x: 159.0, y: 382.0, width: 58.0, height: 29.0))
        tile23.backgroundColor = UIColor.clearColor()
        tile23.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        tile23.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        tile23.shapeLayer.lineCap = "round"
        tile23.shapeLayer.lineJoin = "round"
        tile23.shapeLayer.lineWidth = 1.0
        tile23.shapeLayer.path = CGPathCreateWithSVGString("M0.0508833450877687,28.9491166549122 c-0.0281020955123522,0.0281020955123488,-0.0279918400256095,0.0508833450877688,0.000246262522219445,0.0508833450877688 l57.89774078478,0.0 c0.0282381025478315,0.0,0.0283483580345774,-0.02278124957542,0.000246262522225038,-0.0508833450877688 l-28.8982333098245,-28.8982333098245 c-0.0281020955123523,-0.0281020955123522,-0.0736645946631889,-0.0281020955123522,-0.101766690175538,0.0 l-28.8982333098245,28.8982333098245 z")
        addSubview(tile23)
        tile22 = ShapeView(frame: CGRect(x: 251.0, y: 435.0, width: 57.0366059357401, height: 28.5880099971274))
        tile22.backgroundColor = UIColor.clearColor()
        tile22.transform = CGAffineTransformMakeRotation(-5.75958653158129)
        tile22.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        tile22.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        tile22.shapeLayer.lineCap = "round"
        tile22.shapeLayer.lineJoin = "round"
        tile22.shapeLayer.lineWidth = 1.0
        tile22.shapeLayer.path = CGPathCreateWithSVGString("M0.220418726028271,0.702488655224442 c-0.386688768863678,-0.386688768863678,-0.251774335889365,-0.702488655224442,0.304209953173995,-0.702488655224442 l55.9866027832031,0.0 c0.556658718734965,0.0,0.692183724361968,0.314514884036441,0.304209953173995,0.702488655224442 l-27.5950226895511,27.5950226895511 c-0.386688768863678,0.386688768863678,-1.01700353926091,0.387973771187941,-1.40497731044888,0.0 l-27.5950226895511,-27.5950226895511 z")
        addSubview(tile22)
        tile21 = ShapeView(frame: CGRect(x: 125.482069929196, y: 381.0, width: 57.0366059357401, height: 28.5880099971274))
        tile21.backgroundColor = UIColor.clearColor()
        tile21.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        tile21.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        tile21.shapeLayer.lineCap = "round"
        tile21.shapeLayer.lineJoin = "round"
        tile21.shapeLayer.lineWidth = 1.0
        tile21.shapeLayer.path = CGPathCreateWithSVGString("M0.22041872602827,0.702488655224442 c-0.386688768863678,-0.386688768863678,-0.251774335889351,-0.702488655224442,0.304209953173995,-0.702488655224442 l55.9866027832031,0.0 c0.556658718734973,0.0,0.692183724361968,0.314514884036498,0.304209953173995,0.702488655224442 l-27.5950226895511,27.5950226895511 c-0.386688768863678,0.386688768863678,-1.01700353926091,0.387973771187941,-1.40497731044888,0.0 l-27.5950226895511,-27.5950226895511 z")
        addSubview(tile21)
        tile20 = ShapeView(frame: CGRect(x: 193.0, y: 348.0, width: 58.0, height: 29.0))
        tile20.backgroundColor = UIColor.clearColor()
        tile20.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        tile20.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        tile20.shapeLayer.lineCap = "round"
        tile20.shapeLayer.lineJoin = "round"
        tile20.shapeLayer.lineWidth = 1.0
        tile20.shapeLayer.path = CGPathCreateWithSVGString("M0.0,29.0 l58.0,0.0 -28.9491166549122,-28.9491166549122 c-0.0281020955123523,-0.0281020955123522,-0.0736645946631889,-0.0281020955123522,-0.101766690175538,0.0 l-28.9491166549122,28.9491166549122 z")
        addSubview(tile20)
        tile19 = ShapeView(frame: CGRect(x: 125.0, y: 348.0, width: 58.0, height: 29.0))
        tile19.backgroundColor = UIColor.clearColor()
        tile19.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        tile19.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        tile19.shapeLayer.lineCap = "round"
        tile19.shapeLayer.lineJoin = "round"
        tile19.shapeLayer.lineWidth = 1.0
        tile19.shapeLayer.path = CGPathCreateWithSVGString("M0.0508833450877687,28.9491166549122 c-0.0281020955123522,0.0281020955123488,-0.0279918400256095,0.0508833450877688,0.000246262522219445,0.0508833450877688 l57.89774078478,0.0 c0.0282381025478315,0.0,0.0283483580345774,-0.02278124957542,0.000246262522225038,-0.0508833450877688 l-28.8982333098245,-28.8982333098245 c-0.0281020955123523,-0.0281020955123522,-0.0736645946631889,-0.0281020955123522,-0.101766690175538,0.0 l-28.8982333098245,28.8982333098245 z")
        addSubview(tile19)
        tile18 = ShapeView(frame: CGRect(x: 224.921875, y: 316.0, width: 29.0, height: 58.0))
        tile18.backgroundColor = UIColor.clearColor()
        tile18.transform = CGAffineTransformMakeRotation(-3.14159265358979)
        tile18.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        tile18.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        tile18.shapeLayer.lineCap = "round"
        tile18.shapeLayer.lineJoin = "round"
        tile18.shapeLayer.lineWidth = 1.0
        tile18.shapeLayer.path = CGPathCreateWithSVGString("M0.0508833450877829,0.0508833450877687 c-0.0281020955123522,-0.0281020955123522,-0.0508833450877687,-0.0279918400256095,-0.0508833450877687,0.000246262522219445 l-1.41857997005334e-14,57.89774078478 c-6.9187512541409e-18,0.0282381025478315,0.0227812495754164,0.0283483580345774,0.0508833450877686,0.000246262522225038 l28.8982333098245,-28.8982333098245 c0.0281020955123488,-0.0281020955123523,0.0281020955123488,-0.0736645946631889,0.0,-0.101766690175538 l-28.8982333098245,-28.8982333098245 z")
        addSubview(tile18)
        tile17 = ShapeView(frame: CGRect(x: 190.0, y: 316.0, width: 29.0, height: 58.0))
        tile17.backgroundColor = UIColor.clearColor()
        tile17.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        tile17.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        tile17.shapeLayer.lineCap = "round"
        tile17.shapeLayer.lineJoin = "round"
        tile17.shapeLayer.lineWidth = 1.0
        tile17.shapeLayer.path = CGPathCreateWithSVGString("M0.0508833450877829,0.0508833450877687 c-0.0281020955123522,-0.0281020955123522,-0.0508833450877687,-0.0279918400256095,-0.0508833450877687,0.000246262522219445 l-1.41857997005334e-14,57.89774078478 c-6.9187512541409e-18,0.0282381025478315,0.0227812495754164,0.0283483580345774,0.0508833450877686,0.000246262522225038 l28.8982333098245,-28.8982333098245 c0.0281020955123488,-0.0281020955123523,0.0281020955123488,-0.0736645946631889,0.0,-0.101766690175538 l-28.8982333098245,-28.8982333098245 z")
        addSubview(tile17)
        tile16 = ShapeView(frame: CGRect(x: 157.0, y: 316.0, width: 29.0, height: 58.0))
        tile16.backgroundColor = UIColor.clearColor()
        tile16.transform = CGAffineTransformMakeRotation(-3.14159265358979)
        tile16.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        tile16.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        tile16.shapeLayer.lineCap = "round"
        tile16.shapeLayer.lineJoin = "round"
        tile16.shapeLayer.lineWidth = 1.0
        tile16.shapeLayer.path = CGPathCreateWithSVGString("M0.0508833450877829,0.0508833450877687 c-0.0281020955123522,-0.0281020955123522,-0.0508833450877687,-0.0279918400256095,-0.0508833450877687,0.000246262522219445 l-1.41857997005334e-14,57.89774078478 c-6.9187512541409e-18,0.0282381025478315,0.0227812495754164,0.0283483580345774,0.0508833450877686,0.000246262522225038 l28.8982333098245,-28.8982333098245 c0.0281020955123488,-0.0281020955123523,0.0281020955123488,-0.0736645946631889,0.0,-0.101766690175538 l-28.8982333098245,-28.8982333098245 z")
        addSubview(tile16)
        tile14 = ShapeView(frame: CGRect(x: 193.0, y: 313.0, width: 58.0, height: 28.5880099971274))
        tile14.backgroundColor = UIColor.clearColor()
        tile14.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        tile14.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        tile14.shapeLayer.lineCap = "round"
        tile14.shapeLayer.lineJoin = "round"
        tile14.shapeLayer.lineWidth = 1.0
        tile14.shapeLayer.path = CGPathCreateWithSVGString("M0.0,0.0 l58.0,0.0 -28.2975113447756,28.2975113447756 c-0.386688768863678,0.386688768863678,-1.01700353926091,0.387973771187941,-1.40497731044888,0.0 l-28.2975113447756,-28.2975113447756 z")
        addSubview(tile14)
        tile13 = ShapeView(frame: CGRect(x: 125.482069929196, y: 313.0, width: 57.0366059357401, height: 28.5880099971274))
        tile13.backgroundColor = UIColor.clearColor()
        tile13.transform = CGAffineTransformMakeRotation(-6.28318530717959)
        tile13.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        tile13.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        tile13.shapeLayer.lineCap = "round"
        tile13.shapeLayer.lineJoin = "round"
        tile13.shapeLayer.lineWidth = 1.0
        tile13.shapeLayer.path = CGPathCreateWithSVGString("M0.22041872602827,0.702488655224442 c-0.386688768863678,-0.386688768863678,-0.251774335889351,-0.702488655224442,0.304209953173995,-0.702488655224442 l55.9866027832031,0.0 c0.556658718734973,0.0,0.692183724361968,0.314514884036498,0.304209953173995,0.702488655224442 l-27.5950226895511,27.5950226895511 c-0.386688768863678,0.386688768863678,-1.01700353926091,0.387973771187941,-1.40497731044888,0.0 l-27.5950226895511,-27.5950226895511 z")
        addSubview(tile13)
        tile12 = ShapeView(frame: CGRect(x: 193.0, y: 280.0, width: 58.0, height: 29.0))
        tile12.backgroundColor = UIColor.clearColor()
        tile12.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        tile12.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        tile12.shapeLayer.lineCap = "round"
        tile12.shapeLayer.lineJoin = "round"
        tile12.shapeLayer.lineWidth = 1.0
        tile12.shapeLayer.path = CGPathCreateWithSVGString("M0.0508833450877687,28.9491166549122 c-0.0281020955123522,0.0281020955123488,-0.0279918400256095,0.0508833450877688,0.000246262522219445,0.0508833450877688 l57.89774078478,0.0 c0.0282381025478315,0.0,0.0283483580345774,-0.02278124957542,0.000246262522225038,-0.0508833450877688 l-28.8982333098245,-28.8982333098245 c-0.0281020955123523,-0.0281020955123522,-0.0736645946631889,-0.0281020955123522,-0.101766690175538,0.0 l-28.8982333098245,28.8982333098245 z")
        addSubview(tile12)
        tile11 = ShapeView(frame: CGRect(x: 43.0, y: 239.0, width: 58.0, height: 29.0))
        tile11.backgroundColor = UIColor.clearColor()
        tile11.transform = CGAffineTransformMakeRotation(-5.49778714378214)
        tile11.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        tile11.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        tile11.shapeLayer.lineCap = "round"
        tile11.shapeLayer.lineJoin = "round"
        tile11.shapeLayer.lineWidth = 1.0
        tile11.shapeLayer.path = CGPathCreateWithSVGString("M0.0508833450877687,28.9491166549122 c-0.0281020955123522,0.0281020955123488,-0.0279918400256095,0.0508833450877688,0.000246262522219445,0.0508833450877688 l57.89774078478,0.0 c0.0282381025478315,0.0,0.0283483580345774,-0.02278124957542,0.000246262522225038,-0.0508833450877688 l-28.8982333098245,-28.8982333098245 c-0.0281020955123523,-0.0281020955123522,-0.0736645946631889,-0.0281020955123522,-0.101766690175538,0.0 l-28.8982333098245,28.8982333098245 z")
        addSubview(tile11)
        tile10 = ShapeView(frame: CGRect(x: 159.0, y: 279.0, width: 57.0366059357401, height: 28.5880099971274))
        tile10.backgroundColor = UIColor.clearColor()
        tile10.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        tile10.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        tile10.shapeLayer.lineCap = "round"
        tile10.shapeLayer.lineJoin = "round"
        tile10.shapeLayer.lineWidth = 1.0
        tile10.shapeLayer.path = CGPathCreateWithSVGString("M0.22041872602827,0.702488655224442 c-0.386688768863678,-0.386688768863678,-0.251774335889337,-0.702488655224442,0.304209953173995,-0.702488655224442 l55.9866027832031,0.0 c0.556658718734965,0.0,0.692183724361968,0.314514884036498,0.304209953173995,0.702488655224442 l-27.5950226895511,27.5950226895511 c-0.386688768863678,0.386688768863678,-1.01700353926091,0.387973771187941,-1.40497731044888,0.0 l-27.5950226895511,-27.5950226895511 z")
        addSubview(tile10)
        tile15 = ShapeView(frame: CGRect(x: 107.775702030694, y: 331.224297969306, width: 57.0366059357401, height: 28.5880099971274))
        tile15.backgroundColor = UIColor.clearColor()
        tile15.transform = CGAffineTransformMakeRotation(-1.5707963267949)
        tile15.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        tile15.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        tile15.shapeLayer.lineCap = "round"
        tile15.shapeLayer.lineJoin = "round"
        tile15.shapeLayer.lineWidth = 1.0
        tile15.shapeLayer.path = CGPathCreateWithSVGString("M0.22041872602827,0.702488655224442 c-0.386688768863678,-0.386688768863678,-0.251774335889337,-0.702488655224442,0.304209953173995,-0.702488655224442 l55.9866027832031,0.0 c0.556658718734965,0.0,0.692183724361968,0.314514884036498,0.304209953173995,0.702488655224442 l-27.5950226895511,27.5950226895511 c-0.386688768863678,0.386688768863678,-1.01700353926091,0.387973771187941,-1.40497731044888,0.0 l-27.5950226895511,-27.5950226895511 z")
        addSubview(tile15)
        tile9 = ShapeView(frame: CGRect(x: 159.0, y: 239.0, width: 58.0, height: 29.0))
        tile9.backgroundColor = UIColor.clearColor()
        tile9.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        tile9.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        tile9.shapeLayer.lineCap = "round"
        tile9.shapeLayer.lineJoin = "round"
        tile9.shapeLayer.lineWidth = 1.0
        tile9.shapeLayer.path = CGPathCreateWithSVGString("M0.0508833450877687,28.9491166549122 c-0.0281020955123522,0.0281020955123488,-0.0279918400256095,0.0508833450877688,0.000246262522219445,0.0508833450877688 l57.89774078478,0.0 c0.0282381025478315,0.0,0.0283483580345774,-0.02278124957542,0.000246262522225038,-0.0508833450877688 l-28.8982333098245,-28.8982333098245 c-0.0281020955123523,-0.0281020955123522,-0.0736645946631889,-0.0281020955123522,-0.101766690175538,0.0 l-28.8982333098245,28.8982333098245 z")
        addSubview(tile9)
        tile3 = ShapeView(frame: CGRect(x: 190.0, y: 24.0, width: 28.5880099971274, height: 57.0366059357401))
        tile3.backgroundColor = UIColor.clearColor()
        tile3.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        tile3.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        tile3.shapeLayer.lineCap = "round"
        tile3.shapeLayer.lineJoin = "round"
        tile3.shapeLayer.lineWidth = 1.0
        tile3.shapeLayer.path = CGPathCreateWithSVGString("M0.702488655224442,0.22041872602827 c-0.386688768863678,-0.386688768863678,-0.702488655224442,-0.251774335889337,-0.702488655224442,0.304209953173995 l0.0,55.9866027832031 c0.0,0.556658718734965,0.31451488403647,0.692183724361968,0.702488655224442,0.304209953173995 l27.5950226895511,-27.5950226895511 c0.386688768863678,-0.386688768863678,0.387973771187973,-1.01700353926091,0.0,-1.40497731044888 l-27.5950226895511,-27.5950226895511 z")
        addSubview(tile3)
        tile8 = ShapeView(frame: CGRect(x: 193.482069929196, y: 238.0, width: 57.0366059357401, height: 28.5880099971274))
        tile8.backgroundColor = UIColor.clearColor()
        tile8.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        tile8.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        tile8.shapeLayer.lineCap = "round"
        tile8.shapeLayer.lineJoin = "round"
        tile8.shapeLayer.lineWidth = 1.0
        tile8.shapeLayer.path = CGPathCreateWithSVGString("M0.22041872602827,0.702488655224442 c-0.386688768863678,-0.386688768863678,-0.251774335889337,-0.702488655224442,0.304209953173995,-0.702488655224442 l55.9866027832031,0.0 c0.556658718734965,0.0,0.692183724361968,0.31451488403647,0.304209953173995,0.702488655224442 l-27.5950226895511,27.5950226895511 c-0.386688768863678,0.386688768863678,-1.01700353926091,0.387973771187941,-1.40497731044888,0.0 l-27.5950226895511,-27.5950226895511 z")
        addSubview(tile8)
        tile7 = ShapeView(frame: CGRect(x: 125.482069929196, y: 238.0, width: 57.0366059357401, height: 28.5880099971274))
        tile7.backgroundColor = UIColor.clearColor()
        tile7.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        tile7.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        tile7.shapeLayer.lineCap = "round"
        tile7.shapeLayer.lineJoin = "round"
        tile7.shapeLayer.lineWidth = 1.0
        tile7.shapeLayer.path = CGPathCreateWithSVGString("M0.22041872602827,0.702488655224442 c-0.386688768863678,-0.386688768863678,-0.251774335889351,-0.702488655224442,0.304209953173995,-0.702488655224442 l55.9866027832031,0.0 c0.556658718734973,0.0,0.692183724361968,0.31451488403647,0.304209953173995,0.702488655224442 l-27.5950226895511,27.5950226895511 c-0.386688768863678,0.386688768863678,-1.01700353926091,0.387973771187941,-1.40497731044888,0.0 l-27.5950226895511,-27.5950226895511 z")
        addSubview(tile7)
        tile6 = ShapeView(frame: CGRect(x: 193.0, y: 205.0, width: 58.0, height: 29.0))
        tile6.backgroundColor = UIColor.clearColor()
        tile6.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        tile6.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        tile6.shapeLayer.lineCap = "round"
        tile6.shapeLayer.lineJoin = "round"
        tile6.shapeLayer.lineWidth = 1.0
        tile6.shapeLayer.path = CGPathCreateWithSVGString("M0.0,29.0 l58.0,0.0 -28.9491166549122,-28.9491166549122 c-0.0281020955123523,-0.0281020955123522,-0.0736645946631889,-0.0281020955123522,-0.101766690175538,0.0 l-28.9491166549122,28.9491166549122 z")
        addSubview(tile6)
        tile5 = ShapeView(frame: CGRect(x: 125.0, y: 205.0, width: 58.0, height: 29.0))
        tile5.backgroundColor = UIColor.clearColor()
        tile5.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        tile5.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        tile5.shapeLayer.lineCap = "round"
        tile5.shapeLayer.lineJoin = "round"
        tile5.shapeLayer.lineWidth = 1.0
        tile5.shapeLayer.path = CGPathCreateWithSVGString("M0.0508833450877687,28.9491166549122 c-0.0281020955123522,0.0281020955123488,-0.0279918400256095,0.0508833450877688,0.000246262522219445,0.0508833450877688 l57.89774078478,0.0 c0.0282381025478315,0.0,0.0283483580345774,-0.02278124957542,0.000246262522225038,-0.0508833450877688 l-28.8982333098245,-28.8982333098245 c-0.0281020955123523,-0.0281020955123522,-0.0736645946631889,-0.0281020955123522,-0.101766690175538,0.0 l-28.8982333098245,28.8982333098245 z")
        addSubview(tile5)
        tile1 = ShapeView(frame: CGRect(x: 122.0, y: 174.0, width: 28.5880099971274, height: 57.0366059357401))
        tile1.backgroundColor = UIColor.clearColor()
        tile1.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        tile1.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        tile1.shapeLayer.lineCap = "round"
        tile1.shapeLayer.lineJoin = "round"
        tile1.shapeLayer.lineWidth = 1.0
        tile1.shapeLayer.path = CGPathCreateWithSVGString("M0.702488655224457,0.22041872602827 c-0.386688768863678,-0.386688768863678,-0.702488655224442,-0.251774335889337,-0.702488655224442,0.304209953173995 l-1.4210854715202e-14,55.9866027832031 c0.0,0.556658718734965,0.314514884036484,0.692183724361968,0.702488655224442,0.304209953173995 l27.5950226895511,-27.5950226895511 c0.386688768863678,-0.386688768863678,0.387973771187973,-1.01700353926091,0.0,-1.40497731044888 l-27.5950226895511,-27.5950226895511 z")
        addSubview(tile1)
        tile4 = ShapeView(frame: CGRect(x: 225.0, y: 174.0, width: 29.0, height: 58.0))
        tile4.backgroundColor = UIColor.clearColor()
        tile4.transform = CGAffineTransformMakeRotation(-3.14159265358979)
        tile4.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        tile4.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        tile4.shapeLayer.lineCap = "round"
        tile4.shapeLayer.lineJoin = "round"
        tile4.shapeLayer.lineWidth = 1.0
        tile4.shapeLayer.path = CGPathCreateWithSVGString("M0.0508833450877829,0.0508833450877687 c-0.0281020955123522,-0.0281020955123522,-0.0508833450877687,-0.0279918400256095,-0.0508833450877687,0.000246262522219445 l-1.41857997005334e-14,57.89774078478 c-6.9187512541409e-18,0.0282381025478315,0.0227812495754164,0.0283483580345774,0.0508833450877686,0.000246262522225038 l28.8982333098245,-28.8982333098245 c0.0281020955123488,-0.0281020955123523,0.0281020955123488,-0.0736645946631889,0.0,-0.101766690175538 l-28.8982333098245,-28.8982333098245 z")
        addSubview(tile4)
        tile2 = ShapeView(frame: CGRect(x: 157.0, y: 174.0, width: 29.0, height: 58.0))
        tile2.backgroundColor = UIColor.clearColor()
        tile2.transform = CGAffineTransformMakeRotation(-3.14159265358979)
        tile2.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        tile2.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        tile2.shapeLayer.lineCap = "round"
        tile2.shapeLayer.lineJoin = "round"
        tile2.shapeLayer.lineWidth = 1.0
        tile2.shapeLayer.path = CGPathCreateWithSVGString("M0.0508833450877829,0.0508833450877687 c-0.0281020955123522,-0.0281020955123522,-0.0508833450877687,-0.0279918400256095,-0.0508833450877687,0.000246262522219445 l-1.41857997005334e-14,57.89774078478 c-6.9187512541409e-18,0.0282381025478315,0.0227812495754164,0.0283483580345774,0.0508833450877686,0.000246262522225038 l28.8982333098245,-28.8982333098245 c0.0281020955123488,-0.0281020955123523,0.0281020955123488,-0.0736645946631889,0.0,-0.101766690175538 l-28.8982333098245,-28.8982333098245 z")
        addSubview(tile2)
        tile24 = ShapeView(frame: CGRect(x: 157.0, y: 316.0, width: 29.0, height: 58.0))
        tile24.backgroundColor = UIColor.clearColor()
        tile24.alpha = 0.0
        tile24.transform = CGAffineTransformMakeRotation(-3.14159265358979)
        tile24.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 1.0).CGColor
        tile24.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 1.0).CGColor
        tile24.shapeLayer.lineCap = "round"
        tile24.shapeLayer.lineJoin = "round"
        tile24.shapeLayer.lineWidth = 1.0
        tile24.shapeLayer.path = CGPathCreateWithSVGString("M0.0508833450877829,0.0508833450877687 c-0.0281020955123522,-0.0281020955123522,-0.0508833450877687,-0.0279918400256095,-0.0508833450877687,0.000246262522219445 l-1.41857997005334e-14,57.89774078478 c-6.9187512541409e-18,0.0282381025478315,0.0227812495754164,0.0283483580345774,0.0508833450877686,0.000246262522225038 l28.8982333098245,-28.8982333098245 c0.0281020955123488,-0.0281020955123523,0.0281020955123488,-0.0736645946631889,0.0,-0.101766690175538 l-28.8982333098245,-28.8982333098245 z")
        addSubview(tile24)
        tile25 = ShapeView(frame: CGRect(x: 107.775702030694, y: 331.224297969306, width: 57.0366059357401, height: 28.5880099971274))
        tile25.backgroundColor = UIColor.clearColor()
        tile25.alpha = 0.0
        tile25.transform = CGAffineTransformMakeRotation(-1.5707963267949)
        tile25.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 1.0).CGColor
        tile25.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 1.0).CGColor
        tile25.shapeLayer.lineCap = "round"
        tile25.shapeLayer.lineJoin = "round"
        tile25.shapeLayer.lineWidth = 1.0
        tile25.shapeLayer.path = CGPathCreateWithSVGString("M0.22041872602827,0.702488655224442 c-0.386688768863678,-0.386688768863678,-0.251774335889337,-0.702488655224442,0.304209953173995,-0.702488655224442 l55.9866027832031,0.0 c0.556658718734965,0.0,0.692183724361968,0.314514884036498,0.304209953173995,0.702488655224442 l-27.5950226895511,27.5950226895511 c-0.386688768863678,0.386688768863678,-1.01700353926091,0.387973771187941,-1.40497731044888,0.0 l-27.5950226895511,-27.5950226895511 z")
        addSubview(tile25)
        tile26 = ShapeView(frame: CGRect(x: 122.0, y: 174.0, width: 28.5880099971274, height: 57.0366059357401))
        tile26.backgroundColor = UIColor.clearColor()
        tile26.alpha = 0.0
        tile26.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 1.0).CGColor
        tile26.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 1.0).CGColor
        tile26.shapeLayer.lineCap = "round"
        tile26.shapeLayer.lineJoin = "round"
        tile26.shapeLayer.lineWidth = 1.0
        tile26.shapeLayer.path = CGPathCreateWithSVGString("M0.702488655224457,0.22041872602827 c-0.386688768863678,-0.386688768863678,-0.702488655224442,-0.251774335889337,-0.702488655224442,0.304209953173995 l-1.4210854715202e-14,55.9866027832031 c0.0,0.556658718734965,0.314514884036484,0.692183724361968,0.702488655224442,0.304209953173995 l27.5950226895511,-27.5950226895511 c0.386688768863678,-0.386688768863678,0.387973771187973,-1.01700353926091,0.0,-1.40497731044888 l-27.5950226895511,-27.5950226895511 z")
        addSubview(tile26)
    }

    public override func intrinsicContentSize() -> CGSize {
        return Defaults.size
    }
}
