// Generated by C4Studio.
//
// DO NOT MODIFY, your changes will be lost when this file is regenerated.
//

import UIKit


public class BeginViewController: UIViewController {
    @IBOutlet public weak var begin: BeginView!
    public var transition: Transition1!

    public override func viewDidLoad() {
        super.viewDidLoad()
        transition = Transition1(view: begin)
    }

    @IBAction public func performTransition(sender: AnyObject?) {
        transition.animate()
    }
}
