// Generated by C4Studio.
//
// DO NOT MODIFY, your changes will be lost when this file is regenerated.
//

import UIKit


public class Transition1: Transition {
    public var view: BeginView

    public init() {
        view = BeginView()
    }

    public init(view: BeginView) {
        self.view = view
    }

    public func reset() {
        let view = self.view
        view.tile4.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        view.tile4.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        view.tile15.alpha = 1.0
        view.tile16.alpha = 1.0
        view.tile1.alpha = 1.0
        view.tile24.alpha = 0.0
        view.tile26.alpha = 0.0
        view.tile25.alpha = 0.0
        view.tile23.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        view.tile23.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        view.tile20.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        view.tile20.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        view.tile19.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        view.tile19.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        view.tile14.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        view.tile14.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        view.tile13.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        view.tile13.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        view.tile10.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        view.tile10.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        view.tile8.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        view.tile8.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        view.tile7.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        view.tile7.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        view.tile6.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        view.tile6.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        view.tile18.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        view.tile18.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        view.tile9.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        view.tile9.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        view.tile21.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        view.tile21.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        view.tile17.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        view.tile17.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        view.tile12.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        view.tile12.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        view.tile5.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        view.tile5.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        view.tile22.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        view.tile22.shapeLayer.position.y = 449.294004998564
        view.tile22.shapeLayer.position.x = 279.51830296787
        view.tile22.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        view.tile22.transform = CGAffineTransformMakeRotation(-5.75958653158129)
        view.tile2.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        view.tile2.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        view.tile3.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        view.tile3.shapeLayer.position.y = 52.51830296787
        view.tile3.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 0.0).CGColor
        view.tile11.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 0.0).CGColor
        view.tile11.shapeLayer.position.y = 253.5
        view.tile11.shapeLayer.position.x = 72.0
        view.tile11.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 0.0).CGColor
        view.tile11.transform = CGAffineTransformMakeRotation(-5.49778714378214)
    }

    public func animate() {
        let view = self.view
        Animation(delay: 0.0, duration: 1.24948396697389, curve: .EaseInOut) {
            view.tile4.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 1.0).CGColor
            view.tile4.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 1.0).CGColor
        }.animate()
        Animation(delay: 0.0, duration: 1.5, curve: .Linear) {
            view.tile15.alpha = 0.0
            view.tile16.alpha = 0.0
            view.tile1.alpha = 0.0
            view.tile24.alpha = 1.0
            view.tile26.alpha = 1.0
            view.tile25.alpha = 1.0
        }.animate()
        Animation(delay: 0.0, duration: 1.5, curve: .EaseInOut) {
            view.tile23.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 1.0).CGColor
            view.tile23.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 1.0).CGColor
            view.tile20.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 1.0).CGColor
            view.tile20.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 1.0).CGColor
            view.tile19.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 1.0).CGColor
            view.tile19.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 1.0).CGColor
            view.tile14.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 1.0).CGColor
            view.tile14.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 1.0).CGColor
            view.tile13.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 1.0).CGColor
            view.tile13.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 1.0).CGColor
            view.tile10.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 1.0).CGColor
            view.tile10.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 1.0).CGColor
            view.tile8.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 1.0).CGColor
            view.tile8.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 1.0).CGColor
            view.tile7.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 1.0).CGColor
            view.tile7.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 1.0).CGColor
            view.tile6.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 1.0).CGColor
            view.tile6.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 1.0).CGColor
        }.animate()
        Animation(delay: 0.0, duration: 0.651023665514593, curve: .EaseIn) {
            view.tile18.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 1.0).CGColor
            view.tile18.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 1.0).CGColor
            view.tile9.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 1.0).CGColor
            view.tile9.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 1.0).CGColor
        }.animate()
        Animation(delay: 0.0, duration: 0.390703004620271, curve: .EaseIn) {
            view.tile21.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 1.0).CGColor
            view.tile21.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 1.0).CGColor
        }.animate()
        Animation(delay: 0.0, duration: 0.900204613095237, curve: .EaseInOut) {
            view.tile17.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 1.0).CGColor
            view.tile17.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 1.0).CGColor
            view.tile12.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 1.0).CGColor
            view.tile12.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 1.0).CGColor
        }.animate()
        Animation(delay: 0.201021865399386, duration: 1.29897813460061, curve: .EaseInOut) {
            view.tile5.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 1.0).CGColor
            view.tile5.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 1.0).CGColor
        }.animate()
        Animation(delay: 0.399715581797236, duration: 1.10028441820276, curve: .EaseInOut) {
            view.tile22.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 1.0).CGColor
            view.tile22.shapeLayer.position.y = 395.294004998564
            view.tile22.shapeLayer.position.x = 222.000372897066
            view.tile22.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 1.0).CGColor
            view.tile22.transform = CGAffineTransformMakeRotation(-0.0)
        }.animate()
        Animation(delay: 0.49972398233487, duration: 1.00027601766513, curve: .EaseInOut) {
            view.tile2.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 1.0).CGColor
            view.tile2.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 1.0).CGColor
        }.animate()
        Animation(delay: 0.599912394393241, duration: 0.900087605606759, curve: .Linear) {
            view.tile3.shapeLayer.strokeColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 1.0).CGColor
            view.tile3.shapeLayer.position.y = 202.51830296787
            view.tile3.shapeLayer.fillColor = UIColor(red: 0.313725490196078, green: 0.498039215686275, blue: 0.392156862745098, alpha: 1.0).CGColor
        }.animate()
        Animation(delay: 0.600086405529956, duration: 0.899913594470044, curve: .EaseInOut) {
            view.tile11.shapeLayer.strokeColor = UIColor(red: 1.0, green: 0.749019607843137, blue: 0.282352941176471, alpha: 1.0).CGColor
            view.tile11.shapeLayer.position.y = 294.5
            view.tile11.shapeLayer.position.x = 154.0
            view.tile11.shapeLayer.fillColor = UIColor(red: 1.0, green: 0.768627450980392, blue: 0.329411764705882, alpha: 1.0).CGColor
            view.tile11.transform = CGAffineTransformMakeRotation(-0.0)
        }.animate()
    }
}
